### ISSUE TITLE
期待支持Uptime Kuma登錄猜解

### ISSUE THREAD

**Issue by xirotech** [sockx/wsfuzz#1]
RT

**Comment by sockx** [comment]
👋 我增加了对Uptime Kuma的登陆爆破.

携带 -d 参数能够启用debug查看更详细的数据,但是登陆字典部分需要继续完善.

![image](https://github.com/sockx/wsfuzz/assets/32082618/8b7c70e9-0934-4e00-b2f8-7aeef5c13e53)
![image](https://github.com/sockx/wsfuzz/assets/32082618/0f1e62ab-738e-408f-8dbe-ea4b6938b3c2)
